<footer>
    <div class="conteneur-footer">
        <div class="conteneur-logo">
            <a href="/"><img src="../assets/img/logo/logo_portfolio_couleur.png" alt="img_fond" class="logo"></a>
        </div>
        <div class="copyright">
            <p><i class="fa-solid fa-copyright"></i> 2025 Maylis Gaillard. <br> Tous droits réservés.</p>
        </div>
        <div class="conteneur-rs-ml">
            <div class="footer-reseaux-sociaux">
                <p class="titre-reseaux">Me retrouver</p>
                <div class="contenu-ico-footer">
                    <div class="reseaux-sociaux">
                        <a href="https://www.linkedin.com/company/maylis-g" target="_blank" class="linkedin"><i class="fa-brands fa-linkedin icone-linkedin"></i><p class="legend-reseaux">Linkedin</p></a>
                        <a href="https://github.com/Gaillard05" target="_blank" class="github"><i class="fa-brands fa-github icone-github"></i><p class="legend-reseaux">Github</p></a>
                    </div>
                    <div class="reseaux-sociaux">
                        <a href="https://www.instagram.com/mgdigit" target="_blank" class="instagram"><i class="fa fa-instagram icone-insta"></i><p class="legend-reseaux">Instagram</p></a>
                        <a href="https://www.facebook.com/MaylisGDigit" target="_blank" class="facebook"><i class="fa-brands fa-facebook icone-facebook"></i><p class="legend-reseaux">Facebook</p></a>
                    </div>
                </div>
            </div>
            <div class="footer-mentions-legales">
                <p class="titre-pol-conf">Mentions légales</p>
                <a href="/mentions-legales" class="mentions"><i class="fa-solid fa-file-lines"></i><p class="legend-mentions">Mentions</p></a>
            </div>
        </div>
    </div>
</footer>
</body>
    <script src="https://kit.fontawesome.com/cdec068a4b.js" crossorigin="anonymous"></script>
    <script src="../assets/js/menu_burger.js"></script>
    <script src="../assets/js/btn_scroll_haut.js"></script>
    <script src="../assets/js/animation_affichage_text.js"></script>
    <script src="../assets/js/form_errors.js"></script>
    <script src="../assets/js/formatage_url.js"></script>
</html>