<footer>
    <div class="conteneur-footer">
        <div class="conteneur-logo">
            <a href="/"><img src="../assets/img/logo/logo_portfolio_couleur.png" alt="img_fond" class="logo"></a>
        </div>
        <div class="copyright">
            <p><i class="fa-solid fa-copyright"></i> 2025 Maylis Gaillard. <br> Tous droits réservés.</p>
        </div>
        <div class="conteneur-reseaux-sociaux">
            <div class="titre-contenu-reseaux">
                <p class="titre-reseaux">Me retrouver</p>
            </div>
            <div class="footer-reseaux-sociaux">
                <a href="https://fr.linkedin.com/in/maylis-gaillard"><i class="fa-brands fa-linkedin icone-linkedin"></i></a>
                <a href="https://github.com/Gaillard05"><i class="fa-brands fa-github icone_github"></i></a>
            </div>
        </div>
    </div>
</footer>
</body>
    <script src="https://kit.fontawesome.com/cdec068a4b.js" crossorigin="anonymous"></script>
    <script src="../assets/js/menu_burger.js"></script>
    <script src="../assets/js/btn_scroll_haut.js"></script>
    <script src="../assets/js/animation_affichage_text.js"></script>
    <script src="../assets/js/form_errors.js"></script>
    <script src="../assets/js/formatage_url.js"></script>
</html>