<?php
include_once "../app/views/header/header.phtml";
?>

<main>
    <section class="projet" id="projet">
        <h2>Mon projet</h2>
        <div class="contenus-projet">
            <div class="contenu-img-projet">
                <img src="https://placehold.co/600x400" alt="image-projet" class="img-projet">
            </div>
            <div class="contenu-projet">
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Repudiandae in ea tempore esse? Adipisci ullam maxime id quibusdam consectetur ducimus maiores sapiente totam praesentium recusandae, architecto possimus assumenda, incidunt enim.
                    Exercitationem ea debitis nemo deserunt molestiae quod vel beatae sint incidunt dicta numquam repellat, sequi cum veritatis. Debitis, ducimus tenetur iure illum voluptates dolorem, praesentium quae magnam quod exercitationem velit?
                </p>
            </div>
        </div>
    </section>
</main>


<?php
include_once "../app/views/footer/footer.phtml";
?>