<?php
include_once "../app/views/header/header.phtml";
?>

<main>
    <section class="mentions-legales">
            <h2 class="titre-mentions-legales">Mentions légales</h2>
        <div class="contenu-editeur">
            <h3 class="titre-editeur">Editeur du site</h3>
            <p>Nom / Prénom : Gaillard Maylis</p>
            <p>Satut : Entrepreneur bénéficiare du CAPE sous couvert d'une couveuse d'entreprise</p>
            <p>Activité : Créer, modifier et maintenir des sites web, applications, logiciels pour les entreprises, associations</p>
            <p>Email: mg.contact.digital@gmail.com</p>
        </div>
        <div class="contenu-mention-relative">
            <h3 class="titre-mention-relative">Mention relative à l'activité</h3>
            <p>L'activité présentée sur ce site est exercée dans le cadre d'un Contrat d'Appui au Projet d'Entreprise (CAPE)</p>
            <p>Activité en couveuse les services proposés sur ce site sont commercialisés par Maylis Gaillard, bénéficiaire de la couveuse France Active Seine-et-Marne Essonne (SIRET: 49811170700028), 10Rue Carnot, 77000 Melun</p>
            <p>Dans le cadre de ce dispositif d'accompagnement à la création d'entreprise, Maylis Gaillard exerce  son activité sous le numéro SIRET et la responsabilité juridique de la couveuse.</p>
            <h4 class="titre-mediation">Médiation de la consommation</h4>
            <p>En cas de litigue, vous pouvez siaisir le médiateur de la consommation désigné par Maylis Gaillard : Stéphanie Barnole, stephanieb@franceactive-seineetmarneessonne.org</p>
            <p>Pour toute question ou réclamation, vous pouvez contacter :
               <br> Le bénéficaire : maylisgaillard@hotmail.fr
               <br> La couveuse : couvemploi@franceactive-seineetmarneessonne.org
            </p>
            <p>Couveuse d'entreprise : Couv'emploi</p>
            <p>Forme juridique : SARL, société à responsabilité limitée</p>
            <p>Siège social : 10 Rue Carnot 77000 Melun</p>
        </div>
        <div class="contenu-objet-site">
            <h3 class="titre-objet-site">Objet du site</h3>
            <p>
                Le présent site est un portfolio vitrine ayant pour objectif de présenter les compétences, projets et réalisation de Gaillard Maylis dans le domaine du développement.
                Il ne propose aucune vente en ligne. Toute prise de contact ou demande de prestation s'effectue à titre informatif et exploratoire.
            </p>
        </div>
        <div class="contenu-directeur">
            <h3 class="titre-directeur">Directrice de la publication</h3>
            <p>Gaillard Maylis</p>
        </div>
        <div class="contenu-hebergeur">
            <h3 class="titre-hebergeur">Hébergement</h3>
            <p>Hébergeur : Github Pages (Github, Inc)</p>
        </div>
        <div class="contenu-prop-intel">
            <h3 class="titre-prop-intel">Propriété intellectuelle</h3>
            <p>L'ensemble des contenus présents sur ce site (textes, visuels, projets, logos, code, etc.) est la propriété exclusive de Gaillard Maylis, sauf mention contraire.</p>
            <p>Toute reproduction, représentation ou utilisation, totale ou partielle, sans autorisation préalable écrite est interdite.</p>
        </div>
        <div class="contenu-respon">
            <h3 class="titre-respon">Responsabilité</h3>
            <p>Les informations présentées sur ce site sont fournies à titre indicatif et peuvent être amenées à évoluer.</p>
            <p>Gaillard Maylis ne saurait être tenu responsable de l'utilisation faite des informations diffusées sur ce site.</p>
        </div>
        <div class="contenu-don-perso">
            <h3 class="titre-don-perso">Données personnelles</h3>
            <p>Ce site peut collecter des données personnelles par courrier électronique.</p>
            <p>Ces données sont utilisées uniquement dans le cadre des échanges professionnels lié au projet d'activité et ne sont ni vendues ni transmises à des tiers.</p>
            <p>Conformément au Règlement Général sur la Protection des Données (RGPD), vous disposez d'un droit d'accès, de rectification et de suppression des données vous concernant.</p>
            <p>Pour exercer ces droits, vous pouvez contacter : maylisgaillard@hotmail.fr</p>
        </div>
    </section>
</main>

<?php
include_once "../app/views/footer/footer.phtml";
?>