<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Maylis Gaillard - Développeuse web junior</title>
    <link rel="stylesheet" href="../assets/css/portfolio.css" type="text/css"/>
    <link href="../assets/fonts/Nunito/Nunito-Regular.ttf"/>
    <link href="../assets/fonts/Inter/Inter_18pt-Regular.ttf"/>
    <link rel="shortcut icon" href="../assets/img/logo/logo_portfolio_couleur_icone.png" type="image/x-png">
</head>
<body>
    <header>
        <div class="conteneur-navbar">
            <div class="conteneur-logo">
                <a href="/"><img src="../assets/img/logo/logo_portfolio_couleur.png" alt="img_fond" class="logo"></a>
            </div>
            <div class="menu-icone">
                <i class="fa-solid fa-bars"></i>
            </div>
            <div class="menu-desktop">
                <nav class="menu-principal">
                    <a href="/accueil">Accueil</a>
                    <a href="/a-propos">A propos de moi</a>
                    <a href="/projets">Projets</a>
                    <a href="/contact">Contact</a>
                </nav>
            </div>
        </div>
        <div class="menu-mobile menu-hidden">
            <nav class="menu">
                <a href="/accueil">Accueil</a>
                <a href="/a-propos">A propos de moi</a>
                <a href="/projets">Projets</a>
                <a href="/contact">Contact</a>
            </nav>
        </div>
    </header>