<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Maylis Gaillard - Développeuse web</title>
    <link rel="stylesheet" href="../assets/css/portfolio.css" type="text/css"/>
    <link href="../assets/fonts/Nunito/Nunito-Regular.ttf"/>
    <link href="../assets/fonts/Inter/Inter_18pt-Regular.ttf"/>
    <link rel="shortcut icon" href="../assets/img/logo/logo_portfolio_couleur_icone.png" type="image/x-png">
</head>
<body>
    <main>
        <section class="erreurs">
            <h2>Erreur 405 : Méthode non trouvée</h2>
        </section>
    </main>
</body>
<script src="https://kit.fontawesome.com/cdec068a4b.js" crossorigin="anonymous"></script>
</html>